[package]
name = "byo-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = "0.80.1"
softbuffer = "0.4.6"
winit = "0.30.7"
